### PR TITLE
clean up GL JS state onRemove

### LINKED ISSUE #141: Fix bug causing sources to remain on map after control is removed
From issue reported here: https://github.com/mapbox/mapbox-gl-js/issues/5089

`onRemove` should clean up the sources that this control adds to the map.

### PR DESCRIPTION
**Pull request by mollymerp**
fix #141 

still need to add tests

### CODE REVIEW

**Comment by bryantAXS** [comment]
Would love to see this merged :D

**Comment by lilessam** [comment]
Still getting `Uncaught Error: There is already a source with this ID` even after using v3.1.2 which was released two days ago.

**Comment by mollymerp** [comment]
v3.1.2 was released last June. I'm afraid if you want to take advantage of this change you'll need to use a build from `master` for now, but we'll try to get a new release out soon.

**Comment by lilessam** [comment]
Okay, Here's a workaround (Inspired by this pull request) if anyone interested till you publish a new release.
```Javascript
map.removeControl(directions_control)
map.removeLayer('directions-route-line');
map.removeLayer('directions-route-line-alt');
map.removeLayer('directions-hover-point-casing');
map.removeLayer('directions-hover-point');
map.removeLayer('directions-waypoint-point-casing');
map.removeLayer('directions-waypoint-point');
map.removeLayer('directions-origin-point');
map.removeLayer('directions-origin-label');
map.removeLayer('directions-destination-point');
map.removeLayer('directions-destination-label');
if (map.getSource('directions')) map.removeSource('directions');
```

**Pull request merged**
