### PR TITLE
upgrade directions plugin to v5 of the directions api, make traffic default profile

### PR DESCRIPTION
**Pull request by mollymerp**
screen shot 2017-02-01 at 12 57 12 pm

Here's what the new UI looks like w the additional profile. 

cc @aaronlidman @tristen

### CODE REVIEW

**Comment by aaronlidman** [comment]
Awesome! Thanks for grabbing this.

**Comment by tristen** [comment]
Sweet! I guess I was thinking "Driving" would just use `driving-traffic` instead of it being it's own separate option. This plugin is largely for demonstration though so maybe it makes sense to have it the way you've set it up.

**Comment by mollymerp** [comment]
Yeah, I thought about removing the regular `driving` option altogether – @aaronlidman what do you think? The benefit to this approach is that users will notice that we have traffic-aware directions, but if that is not a priority it would probably be better to drop the regular `driving` profile.

**Comment by aaronlidman** [comment]
Yeah I think mirroring our available APIs is best, seeing as how `driving-traffic` isn't at feature parity with `driving` yet.

**Pull request merged**
